# Generated by Django 4.2.6 on 2023-10-14 16:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0004_alter_answer_options_alter_category_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='technique',
            field=models.IntegerField(choices=[(0, 'MultiPle Choice Question')], default=0, verbose_name='Type of Question'),
        ),
    ]
